name: abc_upi_simnumber
description: Android Specific - Sim Details info Package.
version: 0.0.2
publish_to: https://onepub.dev/api/suosdavuhn/

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.adityabirlacapital.simnumber
        pluginClass: SimNumberPlugin
